version: '3'
services:
  dev:
    build: docker
    network_mode: "host"
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - .:/project
#      - /dev/bus/usb:/dev/bus/usb
    working_dir: "/project"
    environment:
      DISPLAY: $DISPLAY
      TERM: xterm-256color
      PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
